<?php
/**
*Admin will handle all functions for maintaining the backend of the site
 *@author Mike Conway
 *@copyright 2008, Mike Conway
 *@since 05-May-2008
 */

 class Admin{
 
	public static function GetUserList(){
		//return array fro smarty
		$DB = DBCreator::GetDbObject();
		$result = $DB->prepare("select uid from ".DB_PREFIX."_user");
		$result->execute();
		$output = array();
		while ($row = $result->fetch(PDO::FETCH_ASSOC)){
			$output[$row['uid']] = new User($row['uid']); //Create an array of user objects
		}
		return $output;
	}
	public static function DeleteObject($table, $field, $id){
		$DB = DBCreator::GetDbObject();
		$deleteUser = $DB->prepare("delete from ".DB_PREFIX."_$table where `$field`=:id");
		$deleteUser->bindParam(':id', $id);
		$deleteUser->execute();
		if ($deleteUser->rowCount()==1){
			return true;
		}else{
			return false;
		}
	}
	public static function EncodeConfParams($param){
		return base64_encode(str_rot13($param));
	}
	public static function WriteConfig($params){
		$cleanurl = $params['cleanurl'] ? 'true' : 'false';
		$conf = <<<EOF
			<?php
			/*
			 *This is the WiredCMS config file. 
			 *This file is autogenerated at installation - and cannot be manually edited after install
			 *To edit this file with the Web Form, log in as admin, go to the Admin page | Settings
			 *
			 *@author Mike Conway
			 *@copyright Mike Conway - Wiredbyte
			 *@since Jun 3, 2008
			*/
			\$dbuser = '{$params['dbuser']}';
			\$dbpass =  '{$params['dbpass']}';
			\$dbhost = '{$params['dbhost']}';
			\$dbname = '{$params['dbname']}';
			\$dbprefix = '{$params['dbprefix']}';
			\$defaultdir = '{$params['path']}';
			\$sitename = '{$params['sitename']}';
			\$siteslogan = '{$params['siteslogan']}';
			\$sitedomain = '{$params['sitedomain']}';
			\$cleanurl = '{$cleanurl}';
			\$filetypes = '{$params['filetypes']}';
			\$filesize = '{$params['filesize']}';
			\$uploadpath = '{$params['uploadpath']}';
			
			?>
EOF;
		$fh = fopen('./includes/config.inc.php', 'w');
		fwrite($fh, $conf);
		fclose($fh);
	}
}