<?php
/*
 *This is the Nanobyte configuration file. 
 *This file is autogenerated at installation - and cannot be manually edited after install
 *To edit this file with the Web Form, log in as admin, go to the Admin page | Settings
 *
 *@author Mike Conway
 *@since Jun 3, 2008
*/
define("DB_USER", 'ZWJiZw==');
define("DB_PASS", 'cXBtNndl');
define("DB_HOST", 'localhost');
define("DB_NAME", 'nanobyte');
define("DB_PREFIX", 'cms');

define("PATH", 'NanobyteCMS/');
define("SITE_NAME", 'Nanobyte');
define("SITE_SLOGAN", 'The Wiredbyte CMS');
define("SITE_DOMAIN", 'http://dev.wiredbyte.local');
define("SITE_LOGO", 'templates/NanobyteBlue/images/nanobyte_small.png');
define("UPLOAD_PATH", 'files/');
define("FILE_TYPES", '.jpg, .gif, .png, .bmp, .jpeg');
define("FILE_SIZE", '524288');
define("CLEANURL", '1');
define("COMPRESS", '');

define("THEME_PATH", 'templates/NanobyteBlue');
define("DEFAULT_GROUP", '2');
define("SESS_TTL", '0');
define("PEAR_PATH", '');
define("LIMIT", '10');
define("HOME","content");

define("CMS_INSTALLED",'1');

define("EMAIL_FROM",'noreply@wiredbyte.com');
define("EMAIL_SUBJECT",'Auto generated Email from the Nanobyte CMS');
define("EMAIL_IS_HTML",'');

define("SMTP_AUTH",'1');
define("SMTP_SERVER",'208.97.132.208');
define("SMTP_PORT",'25');
define("SMTP_USER",'Ymhnb2JoYXFAanZlcnFvbGdyLnBieg==');
define("SMTP_PASS",'YmNndmJhbnk=');

define('ALLOWED_HTML_TAGS','<a><p><ul><img><center><br><li>');
?>