<?php
/*
 *This is the Nanobyte configuration file. 
 *This file is autogenerated at installation - and cannot be manually edited after install
 *To edit this file with the Web Form, log in as admin, go to the Admin page | Settings
 *
 *@author Mike Conway
 *@since Jun 3, 2008
*/
define("DB_USER", '');
define("DB_PASS", '');
define("DB_HOST", 'localhost');
define("DB_NAME", '');
define("DB_PREFIX", '');

define("PATH", 'NanobyteCMS/');
define("SITE_NAME", '');
define("SITE_SLOGAN", '');
define("SITE_DOMAIN", '');
define("SITE_LOGO", 'templates/NanobyteBlue/images/nanobyte_small.png');
define("UPLOAD_PATH", 'files/');
define("FILE_TYPES", '.jpg, .gif, .png, .bmp, .jpeg');
define("FILE_SIZE", '524288');
define("CLEANURL", '1');
define("COMPRESS", '');

define("THEME_PATH", 'templates/NanobyteBlue');
define("DEFAULT_GROUP", '2');
define("SESS_TTL", '0');
define("PEAR_PATH", '');
define("LIMIT", '10');
define("HOME","content");

define("CMS_INSTALLED",'0');

define("EMAIL_FROM",'');
define("EMAIL_SUBJECT",'');
define("EMAIL_IS_HTML",'');

define("SMTP_AUTH",'0');
define("SMTP_SERVER",'');
define("SMTP_PORT",'25');
define("SMTP_USER",'');
define("SMTP_PASS",'');

define('ALLOWED_HTML_TAGS','<a><p><ul><img><center><br><li>');
?>